#!/bin/bash
#
# HAgent MCP Server launcher for Verilog Adder
# Generated by setup_verilog_mcp.sh

export UV_PROJECT="/Users/ramarevuri/Documents/hagent"
export HAGENT_ROOT="/Users/ramarevuri/Documents/hagent"
export HAGENT_DOCKER="mascucsc/hagent-builder:2025.09"
export HAGENT_EXECUTION_MODE="docker"
export HAGENT_REPO_DIR="/Users/ramarevuri/Documents/hagent/examples/verilog_adder_test"
export HAGENT_BUILD_DIR="/Users/ramarevuri/Documents/hagent/examples/verilog_adder_test/build"
export HAGENT_CACHE_DIR="/Users/ramarevuri/Documents/hagent/examples/verilog_adder_test/cache"
export HAGENT_OUTPUT_DIR="/Users/ramarevuri/Documents/hagent/examples/verilog_adder_test/logs"

echo "Starting HAgent MCP Server for Verilog Adder..."
echo "Repo Dir: ${HAGENT_REPO_DIR}"
echo "Build Dir: ${HAGENT_BUILD_DIR}"
echo "Cache Dir: ${HAGENT_CACHE_DIR}"

# Pass through any command line arguments
uv run python /Users/ramarevuri/Documents/hagent/hagent/mcp/hagent-mcp-server.py "$@"
