#!/bin/bash
#
# Setup script for Verilog Adder MCP server
# Creates the necessary directory structure and configuration files
# for running the HAgent MCP server with Verilog adder example

# Set default values
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HAGENT_ROOT=${HAGENT_ROOT:-$(cd "${SCRIPT_DIR}/../../.." && pwd)}
HAGENT_DOCKER=${HAGENT_DOCKER:-"mascucsc/hagent-builder:2025.09"}

# Use current directory as base
BASE_DIR=${1:-$(pwd)}

echo "Setting up Verilog Adder MCP environment..."
echo "HAGENT_ROOT: ${HAGENT_ROOT}"
echo "BASE_DIR: ${BASE_DIR}"

# Create directory structure
mkdir -p "${BASE_DIR}/build"
mkdir -p "${BASE_DIR}/cache"
mkdir -p "${BASE_DIR}/cache/mcp"
mkdir -p "${BASE_DIR}/logs"

# Path to the MCP server
MCP_SERVER_PATH="${HAGENT_ROOT}/hagent/mcp/hagent-mcp-server.py"

# Create the hagent_server.sh script
cat >"${BASE_DIR}/hagent_server.sh" <<'SCRIPT_EOF'
#!/bin/bash
#
# HAgent MCP Server launcher for Verilog Adder
# Generated by setup_verilog_mcp.sh

export UV_PROJECT="${HAGENT_ROOT}"
export HAGENT_ROOT="${HAGENT_ROOT}"
export HAGENT_DOCKER="${HAGENT_DOCKER}"
export HAGENT_EXECUTION_MODE="docker"
export HAGENT_REPO_DIR="${BASE_DIR}"
export HAGENT_BUILD_DIR="${BASE_DIR}/build"
export HAGENT_CACHE_DIR="${BASE_DIR}/cache"
export HAGENT_OUTPUT_DIR="${BASE_DIR}/logs"

echo "Starting HAgent MCP Server for Verilog Adder..."
echo "Repo Dir: ${HAGENT_REPO_DIR}"
echo "Build Dir: ${HAGENT_BUILD_DIR}"
echo "Cache Dir: ${HAGENT_CACHE_DIR}"

# Pass through any command line arguments
uv run python ${MCP_SERVER_PATH} "$@"
SCRIPT_EOF

# Make the script executable
chmod +x "${BASE_DIR}/hagent_server.sh"

echo
echo "Verilog Adder MCP setup complete!"
echo
echo "Directory structure:"
echo "- ${BASE_DIR}/src (Verilog source files)"
echo "- ${BASE_DIR}/tests (testbench files)"
echo "- ${BASE_DIR}/config (configuration files)"
echo "- ${BASE_DIR}/build (build outputs)"
echo "- ${BASE_DIR}/cache (cached files)"
echo "- ${BASE_DIR}/logs (execution logs)"
echo
echo "Generated files:"
echo "- ${BASE_DIR}/hagent_server.sh (MCP server launcher)"
echo
echo "To use with Gemini:"
echo "  gemini add verilog-adder ${BASE_DIR}/hagent_server.sh"
echo
echo "To test manually:"
echo "  ${BASE_DIR}/hagent_server.sh"
echo
